### ISSUE TITLE
Ambiente de desenvolvimento

### ISSUE THREAD

**Issue by rodolfogordo10** [rodolfogordo10/vilamota#2]

**Comment by felipekm** [comment]
Bora @rodolfogordo10 👯

**Comment by FelipeBrizola** [comment]
kiki é?! hahaha

**Comment by felipekm** [comment]
Gordo :100:

**Comment by talesbaz** [comment]
vamo dale!!!

**Comment by istumpf** [comment]
Coração e alegria!

**Comment by ezequielmross** [comment]
Vai ter paquera!

**Comment by talesbaz** [comment]
![image](https://cloud.githubusercontent.com/assets/6804621/19245889/f3323c46-8ef9-11e6-8ab4-56399c502e0a.png)

**Comment by eduardocrn** [comment]
Vai te!

**Comment by talesbaz** [comment]
MEU APELIDO É SOLARIS

**Comment by evandromello** [comment]
XD

**Comment by felipekm** [comment]
![image](https://cloud.githubusercontent.com/assets/205932/19245906/06e8c124-8efa-11e6-938e-6a3c6eb4ee18.png)

**Comment by talesbaz** [comment]
serei golfista em breve

**Comment by achutti** [comment]
Vai t paquera

**Comment by talesbaz** [comment]
meu irmao tem vergonha de mim

**Comment by felipekm** [comment]
![image](https://cloud.githubusercontent.com/assets/205932/19245912/1446efa8-8efa-11e6-8d3b-58dea23960c7.png)

**Comment by rodolfogordo10** [comment]
LEGAL

**Comment by felipekm** [comment]
![image](https://cloud.githubusercontent.com/assets/205932/19245924/1e31b7f0-8efa-11e6-8112-f44cf54bea33.png)

**Comment by talesbaz** [comment]
![image](https://cloud.githubusercontent.com/assets/6804621/19245929/2279361c-8efa-11e6-8134-af5920b4a280.png)

**Comment by talesbaz** [comment]
![image](https://cloud.githubusercontent.com/assets/6804621/19245942/36ba75e6-8efa-11e6-82f5-15c162dfdd66.png)

**Comment by ezequielmross** [comment]
![image](https://cloud.githubusercontent.com/assets/6461113/19245944/3869ae70-8efa-11e6-819b-d99de21875a7.png)

**Comment by ezequielmross** [comment]
![image](https://cloud.githubusercontent.com/assets/6461113/19245963/54d5cf76-8efa-11e6-9090-a9e07ebe2ffe.png)

**Comment by FelipeBrizola** [comment]
TA SEM LABEL DE TEMPO
